@startuml
start
: Save R1, R2, and R3 in memmory;
: Set R3 to -48;
: Set R0 to point at the output string;
: Print the output string;
: Read the next input from the console and store it in R0;
: Echo R0 back to the console;
: Add the value of R3 to R0;
: Set R2 to 10 and R1 to 0;
repeat
  :Add R0 to R1;
  :Suptract 1 from R2;
repeat while (R2 > 0) is (yes)
->no;
: Read the next input from the console and store it in R0;
: Echo R0 back to the console;
: Add the value of R3 to R0;
: Add the value of R1 to R0;
: Restore the originals values of R1, R2, and R3 from memmory;
stop
@enduml